"""empty message

Revision ID: 177a23c9e62a
Revises: 
Create Date: 2019-09-13 15:45:43.513958

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177a23c9e62a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_discussion_id'), 'comments', ['discussion_id'], unique=False)
    op.create_index(op.f('ix_comments_uid'), 'comments', ['uid'], unique=False)
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('problems', ormtypes.json_pickle.JsonPickle(), nullable=False),
    sa.Column('ranklist_visible', sa.Boolean(), nullable=False),
    sa.Column('judge_result_visible', sa.Boolean(), nullable=False),
    sa.Column('rank_criterion', sa.String(length=20), nullable=False),
    sa.Column('invite_code', sa.String(length=10), nullable=False),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('rated_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('top', sa.Boolean(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_path'), 'discussions', ['path'], unique=False)
    op.create_index(op.f('ix_discussions_title'), 'discussions', ['title'], unique=False)
    op.create_table('mails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mails_from_id'), 'mails', ['from_id'], unique=False)
    op.create_index(op.f('ix_mails_to_id'), 'mails', ['to_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('input_format', sa.Text(), nullable=True),
    sa.Column('output_format', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('example', ormtypes.json_pickle.JsonPickle(), nullable=True),
    sa.Column('files', ormtypes.json_pickle.JsonPickle(), nullable=True),
    sa.Column('downloads', ormtypes.json_pickle.JsonPickle(), nullable=True),
    sa.Column('provides', ormtypes.json_pickle.JsonPickle(), nullable=True),
    sa.Column('subtasks', ormtypes.json_pickle.JsonPickle(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('spj_filename', sa.String(length=20), nullable=True),
    sa.Column('using_file_io', sa.Boolean(), nullable=True),
    sa.Column('input_file_name', sa.String(length=30), nullable=True),
    sa.Column('output_file_name', sa.String(length=30), nullable=True),
    sa.Column('problem_type', sa.String(length=20), nullable=True),
    sa.Column('extra_compile_parameter', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('judge_result', ormtypes.json_pickle.JsonPickle(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('memory_cost', sa.Integer(), nullable=False),
    sa.Column('time_cost', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('judger', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_contest_id'), 'submissions', ['contest_id'], unique=False)
    op.create_index(op.f('ix_submissions_score'), 'submissions', ['score'], unique=False)
    op.create_index(op.f('ix_submissions_uid'), 'submissions', ['uid'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('members', ormtypes.json_pickle.JsonPickle(), nullable=False),
    sa.Column('admins', ormtypes.json_pickle.JsonPickle(), nullable=False),
    sa.Column('tasks', ormtypes.json_pickle.JsonPickle(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('auth_token', sa.String(length=128), nullable=False),
    sa.Column('register_time', sa.DateTime(), nullable=False),
    sa.Column('rating_history', ormtypes.json_pickle.JsonPickle(), nullable=False),
    sa.Column('joined_teams', ormtypes.json_pickle.JsonPickle(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_rating'), 'users', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rating'), table_name='users')
    op.drop_table('users')
    op.drop_table('team')
    op.drop_index(op.f('ix_submissions_uid'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_score'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_contest_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('problems')
    op.drop_index(op.f('ix_mails_to_id'), table_name='mails')
    op.drop_index(op.f('ix_mails_from_id'), table_name='mails')
    op.drop_table('mails')
    op.drop_index(op.f('ix_discussions_title'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_path'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_table('contest')
    op.drop_index(op.f('ix_comments_uid'), table_name='comments')
    op.drop_index(op.f('ix_comments_discussion_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
