"""增加外键update约束条件

Revision ID: 94d8a0728443
Revises: b45814c1fca7
Create Date: 2021-11-15 18:21:13.460347

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '003f4c60ac73'
down_revision = 'b45814c1fca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('account_id', table_name='remote_accounts')
    op.drop_table('remote_accounts')
    op.drop_constraint('submission_ibfk_4', 'submission', type_='foreignkey')
    op.drop_constraint('submission_ibfk_3', 'submission', type_='foreignkey')
    op.create_foreign_key(None, 'submission', 'user', ['uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'submission', 'virtual_contest', ['virtual_contest_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'submission', 'problem', ['problem_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('team_ibfk_1', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'user', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('team_file_ibfk_2', 'team_file', type_='foreignkey')
    op.drop_constraint('team_file_ibfk_1', 'team_file', type_='foreignkey')
    op.drop_constraint('team_file_ibfk_3', 'team_file', type_='foreignkey')
    op.create_foreign_key(None, 'team_file', 'user', ['uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'team_file', 'file_storage', ['file_id'], ['uuid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'team_file', 'team', ['team_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('team_member_ibfk_1', 'team_member', type_='foreignkey')
    op.drop_constraint('team_member_ibfk_2', 'team_member', type_='foreignkey')
    op.create_foreign_key(None, 'team_member', 'user', ['uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'team_member', 'team', ['team_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('virtual_contest_ibfk_1', 'virtual_contest', type_='foreignkey')
    op.drop_constraint('virtual_contest_ibfk_2', 'virtual_contest', type_='foreignkey')
    op.create_foreign_key(None, 'virtual_contest', 'contest', ['contest_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'virtual_contest', 'user', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('wikipage_version_ibfk_2', 'wikipage_version', type_='foreignkey')
    op.drop_constraint('wikipage_version_ibfk_3', 'wikipage_version', type_='foreignkey')
    op.drop_constraint('wikipage_version_ibfk_1', 'wikipage_version', type_='foreignkey')
    op.create_foreign_key(None, 'wikipage_version', 'wiki_navigation_item', ['navigation_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'wikipage_version', 'wikipage', ['wikipage_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'wikipage_version', 'user', ['uid'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wikipage_version', type_='foreignkey')
    op.drop_constraint(None, 'wikipage_version', type_='foreignkey')
    op.drop_constraint(None, 'wikipage_version', type_='foreignkey')
    op.create_foreign_key('wikipage_version_ibfk_1', 'wikipage_version', 'wikipage', ['wikipage_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('wikipage_version_ibfk_3', 'wikipage_version', 'wiki_navigation_item', ['navigation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('wikipage_version_ibfk_2', 'wikipage_version', 'user', ['uid'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'virtual_contest', type_='foreignkey')
    op.drop_constraint(None, 'virtual_contest', type_='foreignkey')
    op.create_foreign_key('virtual_contest_ibfk_2', 'virtual_contest', 'contest', ['contest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('virtual_contest_ibfk_1', 'virtual_contest', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.drop_constraint(None, 'team_member', type_='foreignkey')
    op.create_foreign_key('team_member_ibfk_2', 'team_member', 'user', ['uid'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('team_member_ibfk_1', 'team_member', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'team_file', type_='foreignkey')
    op.drop_constraint(None, 'team_file', type_='foreignkey')
    op.drop_constraint(None, 'team_file', type_='foreignkey')
    op.create_foreign_key('team_file_ibfk_3', 'team_file', 'user', ['uid'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('team_file_ibfk_1', 'team_file', 'file_storage', ['file_id'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key('team_file_ibfk_2', 'team_file', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_ibfk_1', 'team', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.create_foreign_key('submission_ibfk_3', 'submission', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('submission_ibfk_4', 'submission', 'user', ['uid'], ['id'], ondelete='CASCADE')
    op.create_table('remote_accounts',
    sa.Column('account_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('oj', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('uid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session', mysql.VARCHAR(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('account_id', 'remote_accounts', ['account_id'], unique=False)
    # ### end Alembic commands ###
