"""更新主页轮播图设置

Revision ID: 049e9ca2dfd2
Revises: f73d8f44048a
Create Date: 2021-07-01 00:57:35.139562

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '049e9ca2dfd2'
down_revision = 'f73d8f44048a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homepage_swiper', sa.Column('image_url', sa.String(length=200), nullable=False))
    op.add_column('homepage_swiper', sa.Column('link_url', sa.String(length=200), nullable=False))
    op.drop_column('homepage_swiper', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homepage_swiper', sa.Column('url', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('homepage_swiper', 'link_url')
    op.drop_column('homepage_swiper', 'image_url')
    # ### end Alembic commands ###
