"""题解索引

Revision ID: 0a97bf5c2de8
Revises: dd30f04a2e37
Create Date: 2021-07-01 23:20:24.867907

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a97bf5c2de8'
down_revision = 'dd30f04a2e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_problem_solution_uid'), 'problem_solution', ['uid'], unique=False)
    op.create_index(op.f('ix_problem_solution_verified'), 'problem_solution', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_solution_verified'), table_name='problem_solution')
    op.drop_index(op.f('ix_problem_solution_uid'), table_name='problem_solution')
    # ### end Alembic commands ###
