"""取消邮箱唯一限制

Revision ID: 0acef12f3577
Revises: 9767248981d8
Create Date: 2020-10-27 07:55:07.651358

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0acef12f3577'
down_revision = '9767248981d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
