"""增加导航页ID

Revision ID: 16560d40147f
Revises: e1ae35782e6e
Create Date: 2020-09-02 21:39:41.435401

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16560d40147f'
down_revision = 'e1ae35782e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikipage', sa.Column('navigation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wikipage', 'wiki_navigation_item', ['navigation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wikipage', type_='foreignkey')
    op.drop_column('wikipage', 'navigation_id')
    # ### end Alembic commands ###
