"""题目标签支持

Revision ID: 1d853776b0af
Revises: f704cb90eac0
Create Date: 2020-08-19 19:28:26.191126

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d853776b0af'
down_revision = 'f704cb90eac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('display', mysql.LONGTEXT(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problemtag',
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('problem_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problemtag')
    op.drop_table('tag')
    # ### end Alembic commands ###
