"""团队习题集实现

Revision ID: 22ed937444ea
Revises: aacb30cf5f40
Create Date: 2020-10-27 16:49:50.311575

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22ed937444ea'
down_revision = 'aacb30cf5f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_problemsets', ormtypes.json_pickle.JsonPickle(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'team_problemsets')
    # ### end Alembic commands ###
