"""移除不需要的数据列

Revision ID: 334402cb9ed0
Revises: b9bdd6065e1c
Create Date: 2021-10-03 23:24:31.877307

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '334402cb9ed0'
down_revision = 'b9bdd6065e1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_auth_code')
    op.drop_column('user', 'last_send_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_send_time', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('last_auth_code', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=10), nullable=True))
    # ### end Alembic commands ###
