"""empty message

Revision ID: 3e383813bc53
Revises: 7bc5ccd7359e
Create Date: 2019-09-13 20:03:39.421259

"""
from alembic import op
import sqlalchemy as sa
import ormtypes


# revision identifiers, used by Alembic.
revision = '3e383813bc53'
down_revision = '7bc5ccd7359e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('raw_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'raw_admin')
    # ### end Alembic commands ###
