"""私有团队和团

Revision ID: 3f851c5224ac
Revises: d8c6251b95bb
Create Date: 2020-08-20 22:48:40.731612

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f851c5224ac'
down_revision = 'd8c6251b95bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem', 'team', ['team_id'], ['id'])
    op.add_column('team', sa.Column('invite_code', mysql.LONGTEXT, nullable=True))
    op.add_column('team', sa.Column('private', mysql.TINYINT(display_width=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'private')
    op.drop_column('team', 'invite_code')
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'team_id')
    # ### end Alembic commands ###
