"""比赛在线提问

Revision ID: 40632a2cc3f8
Revises: cb1714a64579
Create Date: 2020-10-27 23:44:22.970820

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40632a2cc3f8'
down_revision = 'cb1714a64579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_clarification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('send_time', sa.DateTime(), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('replied', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('replier', sa.Integer(), nullable=True),
    sa.Column('reply_content', mysql.LONGTEXT(), nullable=True),
    sa.Column('reply_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest'], ['contest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replier'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_clarification_contest'), 'contest_clarification', ['contest'], unique=False)
    op.create_index(op.f('ix_contest_clarification_replied'), 'contest_clarification', ['replied'], unique=False)
    op.create_index(op.f('ix_contest_clarification_replier'), 'contest_clarification', ['replier'], unique=False)
    op.create_index(op.f('ix_contest_clarification_reply_time'), 'contest_clarification', ['reply_time'], unique=False)
    op.create_index(op.f('ix_contest_clarification_send_time'), 'contest_clarification', ['send_time'], unique=False)
    op.create_index(op.f('ix_contest_clarification_sender'), 'contest_clarification', ['sender'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_clarification_sender'), table_name='contest_clarification')
    op.drop_index(op.f('ix_contest_clarification_send_time'), table_name='contest_clarification')
    op.drop_index(op.f('ix_contest_clarification_reply_time'), table_name='contest_clarification')
    op.drop_index(op.f('ix_contest_clarification_replier'), table_name='contest_clarification')
    op.drop_index(op.f('ix_contest_clarification_replied'), table_name='contest_clarification')
    op.drop_index(op.f('ix_contest_clarification_contest'), table_name='contest_clarification')
    op.drop_table('contest_clarification')
    # ### end Alembic commands ###
