"""problem增加是否允许查看提交

Revision ID: 4c3a6d07cc13
Revises: 77dd6caa9e91
Create Date: 2020-12-20 18:14:48.188177

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c3a6d07cc13'
down_revision = '77dd6caa9e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('submission_visible', mysql.TINYINT(display_width=1), nullable=False))
    op.create_index(op.f('ix_problem_submission_visible'), 'problem', ['submission_visible'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_submission_visible'), table_name='problem')
    op.drop_column('problem', 'submission_visible')
    # ### end Alembic commands ###
