"""empty message

Revision ID: 58fae4d1a268
Revises: f020d208a7cb
Create Date: 2019-10-19 22:35:19.115345

"""
from alembic import op
import sqlalchemy as sa
import ormtypes


# revision identifiers, used by Alembic.
revision = '58fae4d1a268'
down_revision = 'f020d208a7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn: Connection = op.get_bind()
    op.add_column('submissions', sa.Column('selected_compile_parameters', ormtypes.json_pickle.JsonPickle(), nullable=False))
    conn.execute("""
        update submissions set extra_parameter='[]'
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'selected_compile_parameters')
    # ### end Alembic commands ###
