"""统计最后刷新题目列表的时间

Revision ID: 599d251e19e4
Revises: 334402cb9ed0
Create Date: 2021-10-03 23:25:44.564160

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599d251e19e4'
down_revision = '334402cb9ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_refreshed_cached_accepted_problems', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_refreshed_cached_accepted_problems')
    # ### end Alembic commands ###
