"""关闭比赛

Revision ID: 5bca0c90b54e
Revises: c43dfdc42cab
Create Date: 2020-08-22 21:52:40.807684

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bca0c90b54e'
down_revision = 'c43dfdc42cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('closed', mysql.TINYINT(display_width=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'closed')
    # ### end Alembic commands ###
