"""题解补充

Revision ID: 5e82937bff45
Revises: 0a97bf5c2de8
Create Date: 2021-07-01 23:25:24.073008

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e82937bff45'
down_revision = '0a97bf5c2de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_solution', sa.Column('upload_time', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_problem_solution_upload_time'), 'problem_solution', ['upload_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_solution_upload_time'), table_name='problem_solution')
    op.drop_column('problem_solution', 'upload_time')
    # ### end Alembic commands ###
