"""题解补充

Revision ID: 663e2f408a65
Revises: 5e82937bff45
Create Date: 2021-07-01 23:38:18.352914

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '663e2f408a65'
down_revision = '5e82937bff45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_solution', sa.Column('top', mysql.TINYINT(display_width=1), nullable=False))
    op.create_index(op.f('ix_problem_solution_top'), 'problem_solution', ['top'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_solution_top'), table_name='problem_solution')
    op.drop_column('problem_solution', 'top')
    # ### end Alembic commands ###
