"""添加索引

Revision ID: 67e87203d4e4
Revises: ca42f2bcb76b
Create Date: 2021-10-04 14:24:06.268410

"""
from sqlalchemy.sql.sqltypes import String, Text
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e87203d4e4'
down_revision = 'ca42f2bcb76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file_storage', 'filename',
                    existing_type=String(256),
                    nullable=False)
    op.create_index(op.f('ix_file_storage_filename'),
                    'file_storage', ['filename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_storage_filename'), table_name='file_storage')
    op.alter_column('file_storage', 'filename',
                    existing_type=Text,
                    nullable=False)
    # ### end Alembic commands ###
