"""题目文件记录上传者

Revision ID: 687cd9d8786e
Revises: 599d251e19e4
Create Date: 2021-10-04 12:39:31.802652

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687cd9d8786e'
down_revision = '599d251e19e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_file', sa.Column('uid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'team_file', 'user', ['uid'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_file', type_='foreignkey')
    op.drop_column('team_file', 'uid')
    # ### end Alembic commands ###
