"""团队文件模型

Revision ID: 6cfb0f950a10
Revises: 5328b82a3943
Create Date: 2021-09-28 00:37:19.131438

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfb0f950a10'
down_revision = '5328b82a3943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_storage',
    sa.Column('uuid', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('filesize', sa.BigInteger(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('team_file',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_storage.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_file')
    op.drop_table('file_storage')
    # ### end Alembic commands ###
