"""empty message

Revision ID: 7bc5ccd7359e
Revises: 751ab2a062e3
Create Date: 2019-09-12 21:49:19.819547

"""
from alembic import op
import sqlalchemy as sa
import ormtypes


# revision identifiers, used by Alembic.
revision = '7bc5ccd7359e'
down_revision = '751ab2a062e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contest', sa.Column('rated', sa.Boolean(), nullable=False))
    op.add_column('contest', sa.Column('rated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'rated_time')
    op.drop_column('contest', 'rated')
    # ### end Alembic commands ###
