"""更新密码字段长度

Revision ID: 9212eeda48b2
Revises: 9bb664cd6149
Create Date: 2021-03-12 21:05:33.183206

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9212eeda48b2'
down_revision = '9bb664cd6149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", type_=sa.String(256))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", type_=sa.String(64))
    # ### end Alembic commands ###
