"""百科页面标题

Revision ID: 933014989333
Revises: 16560d40147f
Create Date: 2020-09-02 21:44:52.461986

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '933014989333'
down_revision = '16560d40147f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikipage_version', sa.Column('title', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wikipage_version', 'title')
    # ### end Alembic commands ###
