"""权限包

Revision ID: 97ea3a6c014d
Revises: d6becc4c5751
Create Date: 2020-08-23 19:29:10.757415

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97ea3a6c014d'
down_revision = 'd6becc4c5751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_pack',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', mysql.TEXT, nullable=False),
                    sa.Column("description", mysql.LONGTEXT, nullable=True),
                    sa.Column("permissions",
                              ormtypes.json_pickle.JsonPickle, nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('permission_pack_user',
                    sa.Column('pack_id', sa.Integer(), nullable=False),
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.Column('claimed', mysql.TINYINT(
                        display_width=1), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['pack_id'], ['permission_pack.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('pack_id', 'phone')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission_pack_user')
    op.drop_table('permission_pack')
    # ### end Alembic commands ###
