"""博客

Revision ID: 9f6db39075c7
Revises: 8baad504dc94
Create Date: 2020-09-01 15:37:55.927843

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f6db39075c7'
down_revision = '8baad504dc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussion', sa.Column('blog_private', mysql.TINYINT(display_width=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discussion', 'blog_private')
    # ### end Alembic commands ###
