"""wiki版本追踪

Revision ID: ac28bef87cb9
Revises: c5d936a18918
Create Date: 2020-09-05 15:09:30.698554

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac28bef87cb9'
down_revision = 'c5d936a18918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wikipage_ibfk_2', 'wikipage', type_='foreignkey')
    op.drop_column('wikipage', 'navigation_id')
    op.add_column('wikipage_version', sa.Column('base', mysql.INTEGER(), nullable=True))
    op.add_column('wikipage_version', sa.Column('navigation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wikipage_version', 'wiki_navigation_item', ['navigation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wikipage_version', type_='foreignkey')
    op.drop_column('wikipage_version', 'navigation_id')
    op.drop_column('wikipage_version', 'base')
    op.add_column('wikipage', sa.Column('navigation_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('wikipage_ibfk_2', 'wikipage', 'wiki_navigation_item', ['navigation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
