"""图床数据结构

Revision ID: b45814c1fca7
Revises: 90c08960cf19
Create Date: 2021-11-03 16:50:49.771737

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45814c1fca7'
down_revision = '90c08960cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_store_file',
    sa.Column('file_id', sa.String(length=128), nullable=False),
    sa.Column('thumbnail_id', sa.String(length=128), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_storage.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['file_storage.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_image_store_file_thumbnail_id'), 'image_store_file', ['thumbnail_id'], unique=False)
    op.create_index(op.f('ix_image_store_file_uid'), 'image_store_file', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_store_file_uid'), table_name='image_store_file')
    op.drop_index(op.f('ix_image_store_file_thumbnail_id'), table_name='image_store_file')
    op.drop_table('image_store_file')
    # ### end Alembic commands ###
