"""缓存通过题目列表

Revision ID: b9bdd6065e1c
Revises: 6cfb0f950a10
Create Date: 2021-10-03 23:16:24.913356

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bdd6065e1c'
down_revision = '6cfb0f950a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_accepted_problems',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'problem_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_accepted_problems')
    # ### end Alembic commands ###
