"""关注列增加时间

Revision ID: bb92b366d72b
Revises: 50469ed01650
Create Date: 2020-08-18 13:49:43.533800

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb92b366d72b'
down_revision = '50469ed01650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follower', sa.Column('time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_follower_time'), 'follower', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follower_time'), table_name='follower')
    op.drop_column('follower', 'time')
    # ### end Alembic commands ###
