"""题目邀请码

Revision ID: bf2896221161
Revises: cdf041881b50
Create Date: 2020-08-21 18:45:50.352311

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf2896221161'
down_revision = 'cdf041881b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('invite_code', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'invite_code')
    # ### end Alembic commands ###
