"""团队题目和团队比赛

Revision ID: c43dfdc42cab
Revises: bf2896221161
Create Date: 2020-08-21 20:08:58.275687

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43dfdc42cab'
down_revision = 'bf2896221161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('team_contests', ormtypes.json_pickle.JsonPickle(), nullable=True))
    op.add_column('team', sa.Column('team_problems', ormtypes.json_pickle.JsonPickle(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'team_problems')
    op.drop_column('team', 'team_contests')
    # ### end Alembic commands ###
