"""wiki配置

Revision ID: c5d936a18918
Revises: afd5b8766120
Create Date: 2020-09-03 13:30:39.373918

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5d936a18918'
down_revision = 'afd5b8766120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikiconfig',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('value', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikiconfig')
    # ### end Alembic commands ###
