"""页面版本增加更新提示

Revision ID: c7c3d7af1669
Revises: d9638a91280c
Create Date: 2020-09-07 16:10:03.070431

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7c3d7af1669'
down_revision = 'd9638a91280c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikipage_version', sa.Column('comment', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wikipage_version', 'comment')
    # ### end Alembic commands ###
