"""更新密码字段长度

Revision ID: c87ab92cddfd
Revises: a62480a57b2f
Create Date: 2021-03-12 20:27:49.759183

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87ab92cddfd'
down_revision = '9212eeda48b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", type_=sa.String(256))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", type_=sa.String(64))
    # ### end Alembic commands ###
