"""增加索引

Revision ID: ca42f2bcb76b
Revises: 687cd9d8786e
Create Date: 2021-10-04 12:42:02.407650

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca42f2bcb76b'
down_revision = '687cd9d8786e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_team_file_uid'), 'team_file', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_file_uid'), table_name='team_file')
    # ### end Alembic commands ###
