"""团队存储结构更改

Revision ID: cb1714a64579
Revises: 22ed937444ea
Create Date: 2020-10-27 20:51:07.340966

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb1714a64579'
down_revision = '22ed937444ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_member',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'team_id')
    )
    op.create_index(op.f('ix_team_member_is_admin'), 'team_member', ['is_admin'], unique=False)
    op.drop_column('team', 'admins')
    op.drop_column('team', 'members')
    op.drop_column('user', 'joined_teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('joined_teams', mysql.LONGTEXT(), nullable=False))
    op.add_column('team', sa.Column('members', mysql.LONGTEXT(), nullable=False))
    op.add_column('team', sa.Column('admins', mysql.LONGTEXT(), nullable=False))
    op.drop_index(op.f('ix_team_member_is_admin'), table_name='team_member')
    op.drop_table('team_member')
    # ### end Alembic commands ###
