"""修改外键策略

Revision ID: cdf041881b50
Revises: 3f851c5224ac
Create Date: 2020-08-20 22:50:07.862867

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf041881b50'
down_revision = '3f851c5224ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('problem_ibfk_2', 'problem', type_='foreignkey')
    op.create_foreign_key(None, 'problem', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.create_foreign_key('problem_ibfk_2', 'problem', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
