"""虚拟比赛索引

Revision ID: d6becc4c5751
Revises: f0795e8d4f6f
Create Date: 2020-08-23 13:33:10.742592

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6becc4c5751'
down_revision = 'f0795e8d4f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_virtual_contest_contest_id'), 'virtual_contest', ['contest_id'], unique=False)
    op.create_index(op.f('ix_virtual_contest_owner_id'), 'virtual_contest', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_contest_owner_id'), table_name='virtual_contest')
    op.drop_index(op.f('ix_virtual_contest_contest_id'), table_name='virtual_contest')
    # ### end Alembic commands ###
