"""合并私有题与权限题

Revision ID: d8c6251b95bb
Revises: 1d853776b0af
Create Date: 2020-08-20 22:11:11.003355

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8c6251b95bb'
down_revision = '1d853776b0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['uid'], ['id'], ondelete='CASCADE')
    op.drop_column('problem', 'require_permission')
    op.drop_constraint('problemtag_ibfk_1', 'problemtag', type_='foreignkey')
    op.drop_constraint('problemtag_ibfk_2', 'problemtag', type_='foreignkey')
    op.create_foreign_key(None, 'problemtag', 'problem', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'problemtag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problemtag', type_='foreignkey')
    op.drop_constraint(None, 'problemtag', type_='foreignkey')
    op.create_foreign_key('problemtag_ibfk_2', 'problemtag', 'tag', ['tag_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key('problemtag_ibfk_1', 'problemtag', 'problem', ['problem_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.add_column('problem', sa.Column('require_permission', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'user', ['uid'], ['id'])
    # ### end Alembic commands ###
