"""增加部分索引

Revision ID: d9638a91280c
Revises: ac28bef87cb9
Create Date: 2020-09-06 17:13:27.533743

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9638a91280c'
down_revision = 'ac28bef87cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wikipage_version_base'), 'wikipage_version', ['base'], unique=False)
    op.create_index(op.f('ix_wikipage_version_navigation_id'), 'wikipage_version', ['navigation_id'], unique=False)
    op.create_index(op.f('ix_wikipage_version_verified'), 'wikipage_version', ['verified'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wikipage_version_verified'), table_name='wikipage_version')
    op.drop_index(op.f('ix_wikipage_version_navigation_id'), table_name='wikipage_version')
    op.drop_index(op.f('ix_wikipage_version_base'), table_name='wikipage_version')
    # ### end Alembic commands ###
