"""题解

Revision ID: dd30f04a2e37
Revises: 049e9ca2dfd2
Create Date: 2021-07-01 23:19:21.197696

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd30f04a2e37'
down_revision = '049e9ca2dfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.Column('verified', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('verifier', sa.Integer(), nullable=True),
    sa.Column('verify_time', sa.DateTime(), nullable=True),
    sa.Column('verify_comments', mysql.LONGTEXT(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifier'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_solution_problem_id'), 'problem_solution', ['problem_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_solution_problem_id'), table_name='problem_solution')
    op.drop_table('problem_solution')
    # ### end Alembic commands ###
