"""wiki数据库

Revision ID: e1ae35782e6e
Revises: 840941163f68
Create Date: 2020-09-02 21:36:39.242169

"""
import ormtypes
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1ae35782e6e'
down_revision = '840941163f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_navigation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', mysql.TEXT(), nullable=False),
    sa.Column('menu', ormtypes.json_pickle.JsonPickle(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wiki_navigation_item_priority'), 'wiki_navigation_item', ['priority'], unique=False)
    op.create_table('wikipage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cached_newest_version', sa.Integer(), nullable=True),
    sa.Column('cached_last_modified_time', sa.DateTime(), nullable=True),
    sa.Column('cached_last_modified_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cached_last_modified_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wikipage_cached_newest_version'), 'wikipage', ['cached_newest_version'], unique=False)
    op.create_table('wikipage_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wikipage_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('verified', mysql.TINYINT(display_width=1), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wikipage_id'], ['wikipage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wikipage_version_time'), 'wikipage_version', ['time'], unique=False)
    op.create_index(op.f('ix_wikipage_version_uid'), 'wikipage_version', ['uid'], unique=False)
    op.create_index(op.f('ix_wikipage_version_wikipage_id'), 'wikipage_version', ['wikipage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wikipage_version_wikipage_id'), table_name='wikipage_version')
    op.drop_index(op.f('ix_wikipage_version_uid'), table_name='wikipage_version')
    op.drop_index(op.f('ix_wikipage_version_time'), table_name='wikipage_version')
    op.drop_table('wikipage_version')
    op.drop_index(op.f('ix_wikipage_cached_newest_version'), table_name='wikipage')
    op.drop_table('wikipage')
    op.drop_index(op.f('ix_wiki_navigation_item_priority'), table_name='wiki_navigation_item')
    op.drop_table('wiki_navigation_item')
    # ### end Alembic commands ###
