"""empty message

Revision ID: eba6b07807ed
Revises: 3e383813bc53
Create Date: 2019-10-19 21:16:40.625738

"""
from alembic import op
import sqlalchemy as sa
import ormtypes
from sqlalchemy.dialects import mysql
from sqlalchemy.engine import Connection
# revision identifiers, used by Alembic.
revision = 'eba6b07807ed'
down_revision = '3e383813bc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('extra_parameter',
                                        ormtypes.json_pickle.JsonPickle(), nullable=False))
    op.drop_column('problems', 'extra_compile_parameter')
    conn: Connection = op.get_bind()
    conn.execute("""
        update problems set extra_parameter='[{"lang": "cpp", "name": "C++98", "parameter": "-std=c++98", "force": false}, {"lang": "cpp", "name": "C++11", "parameter": "-std=c++11", "force": false}, {"lang": "cpp", "name": "C++14", "parameter": "-std=c++14", "force": false}, {"lang": "cpp", "name": "C++17", "parameter": "-std=c++17", "force": false}, {"lang": ".*", "name": "O2\u4f18\u5316", "parameter": "-O2", "force": false}]'
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column(
        'extra_compile_parameter', mysql.TEXT(), nullable=False))
    op.drop_column('problems', 'extra_parameter')
    # ### end Alembic commands ###
