"""feed相关索引

Revision ID: f704cb90eac0
Revises: d1252c9c618a
Create Date: 2020-08-19 15:17:44.595899

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f704cb90eac0'
down_revision = 'd1252c9c618a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feed_time'), 'feed', ['time'], unique=False)
    op.create_index(op.f('ix_feed_uid'), 'feed', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_uid'), table_name='feed')
    op.drop_index(op.f('ix_feed_time'), table_name='feed')
    # ### end Alembic commands ###
