"""主页轮播图设置

Revision ID: f73d8f44048a
Revises: c87ab92cddfd
Create Date: 2021-07-01 00:24:58.453252

"""
import ormtypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f73d8f44048a'
down_revision = 'c87ab92cddfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_swiper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage_swiper')
    # ### end Alembic commands ###
