# 最大提交代码长度
MAX_CODE_LENGTH = 100*1024
# 编译时间限制,ms
COMPILE_TIME_LIMIT = 10*1000
# 评测结束后显示的输入\输出\用户输出的长度限制,字符
DISPLAY_DATA_LENGTH_LIMIT = 1000
# 编译结果长度限制,单位字符
COMPILE_RESULT_LENGTH_LIMIT = 500
# SPJ运行时间限制
SPJ_EXECUTE_TIME_LIMIT = 3000
# 在线IDE运行时间限制
IDE_RUN_TIME_LIMIT = 1000*3
# 在线IDE运行内存限制
IDE_RUN_MEMORY_LIMIT = 512
# 在线IDE结果长度限制,chars
IDE_RUN_RESULT_LENGTH_LIMIT = 2000
# 在线IDE参数长度限制
IDE_RUN_COMPILE_PARAMETER_LENGTH_LIMIT = 30
# 自动同步题目文件
AUTO_SYNC_FILES = True
# 用户输出文件最大大小
OUTPUT_FILE_SIZE_LIMIT = 1024*1024*50